const TOGGLE_SIDE_PANEL = "TOGGLE_SIDE_PANEL";
const TOGGLE_LATENCY_SIDEBAR = "TOGGLE_LATENCY_SIDEBAR";
const SELECT_NODE = "SELECT_NODE";
const SHOW_USER_GUIDE='SHOW_USER_GUIDE';
const TOGGLE_RESOURCE_SIDEBAR = "TOGGLE_RESOURCE_SIDEBAR";

export {
 TOGGLE_SIDE_PANEL,
 TOGGLE_LATENCY_SIDEBAR,
 TOGGLE_RESOURCE_SIDEBAR,
 SELECT_NODE,
 SHOW_USER_GUIDE
};
