const TOGGLE_SIDE_PANEL = "TOGGLE_SIDE_PANEL";
const TOGGLE_LATENCY_SIDEBAR = "TOGGLE_LATENCY_SIDEBAR";
const SELECT_NODE = "SELECT_NODE";

export {
 TOGGLE_SIDE_PANEL,
 TOGGLE_LATENCY_SIDEBAR,
 SELECT_NODE
};
