
export const MINI_SIDENAV = "MINI_SIDENAV";
export const WHITE_SIDENAV = "WHITE_SIDENAV";
export const SIDENAV_COLOR = "SIDENAV_COLOR";
export const FIXED_NAVBAR = "FIXED_NAVBAR";
export const OPEN_CONFIGURATOR = "OPEN_CONFIGURATOR";
export const DIRECTION = "DIRECTION";
export const LAYOUT = "LAYOUT";
export const DARKMODE = "DARKMODE";
export const TOGGLE_APP_SIDEBAR = "TOGGLE_APP_SIDEBAR";
