// Define file-related action types
const UPLOAD_FILE = "UPLOAD_FILE";
const LIST_FILES = "LIST_FILES";
const DELETE_FILE = "DELETE_FILE";
const RESET_STATUS = "RESET_STATUS";
const VIEW_FILE = "VIEW_FILE";
const GET_CSV = "GET_CSV";
const SELECT_TO_COMPARE = "SELECT_TO_COMPARE";
const REMOVE_COMPARE_FILE = "REMOVE_COMPARE_FILE";
const TOGGLE_COMPARISON_BOX = "TOGGLE_COMPARISON_BOX";
export {
  REMOVE_COMPARE_FILE,
  SELECT_TO_COMPARE,
  UPLOAD_FILE,
  LIST_FILES,
  DELETE_FILE,
  VIEW_FILE,
  RESET_STATUS,
  GET_CSV,
  TOGGLE_COMPARISON_BOX
};

